# Generated by Django 6.0.7 on 2026-07-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='class_name',
        ),
    ]
